# GitHub Actions workflow for a Python application

name: Python application

on:
  # Trigger the workflow on push to main or release branches, and on tags matching v*.*.*
  push:
    branches: [ "main", "release/**" ]
    tags: [ "v*.*.*" ]
  # Trigger the workflow on pull requests to main or release branches
  pull_request:
    branches: [ "main", "release/**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    # Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Lint the code with flake8
    - name: Lint with flake8
      run: |
        flake8 . --ignore=E501,E402,B950
    # Run tests with pytest and generate a coverage report
    - name: Test with pytest
      run: |
        pytest --cov=. --cov-report=html tests/
    # Upload coverage reports to Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
