name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  python-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

  build:
    needs: python-app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build application
        run: |
          LOG_LEVEL=debug
          if [ "$RUNNER_OS" == "Windows" ]; then
            pyinstaller --add-data "src/data/resources:resources" --icon "src/data/resources/assets/icon.ico" --paths src src/main.py --name CarbonCalculator.exe
          elif [ "$RUNNER_OS" == "macOS" ]; then
            pyinstaller --add-data "src/data/resources:resources" --icon "src/data/resources/assets/icon.icns" --paths src src/main.py --name CarbonCalculator
          else
            pyinstaller --add-data "src/data/resources:resources" --icon "src/data/resources/assets/icon.png" --paths src src/main.py --name CarbonCalculator
          fi
        continue-on-error: true
      - name: Archive build artifacts
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            mkdir -p build
            mv dist/CarbonCalculator.exe build/
          else
            mkdir -p build
            mv dist/CarbonCalculator build/
          fi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CarbonCalculator-${{ matrix.os }}
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: CarbonCalculator-ubuntu-latest
          path: build/linux
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: CarbonCalculator-macos-latest
          path: build/macos
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: CarbonCalculator-windows-latest
          path: build/windows
      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux/CarbonCalculator
          asset_name: CarbonCalculator-linux
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/macos/CarbonCalculator
          asset_name: CarbonCalculator-macos
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/windows/CarbonCalculator.exe
          asset_name: CarbonCalculator-windows.exe
          asset_content_type: application/octet-stream
